name: Build and Create Custom Image

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_packer:
    name: Build Jar and Create Custom Image
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: cloudDatabase
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PKR_VAR_project_id: ${{secrets.project_id}}
      PKR_VAR_source_image: ${{secrets.source_image}}
      PKR_VAR_image_name: ${{secrets.image_name}}
      PKR_VAR_zone: ${{secrets.zone}}
      PKR_VAR_disk_size: ${{secrets.disk_size}}
      PKR_VAR_network: ${{secrets.network}}
      PKR_VAR_communicator: ${{secrets.communicator}}
      PKR_VAR_ssh_username: ${{secrets.ssh_username}}
      PKR_VAR_ssh_password: ${{secrets.ssh_password}}
      PKR_VAR_ssh_timeout: ${{secrets.ssh_timeout}}
      PKR_VAR_service_account_email: ${{secrets.service_account_email}}
      PKR_VAR_service_account_json: ${{secrets.service_account_json}}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start MySQL and create database
        run: |
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DATABASE_USERNAME -p$DATABASE_PASSWORD

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Creating .env file
        run: |
              echo "DATABASE_URL=${{secrets.DATABASE_URL}}" > .env
              echo "DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}" >> .env
              echo "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env
      - name: GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
         credentials_json: '${{secrets.GCP_CREDENTIALS}}'

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup-packer

      - name: Init and Build Custom Image with Packer
        working-directory: ./packer
        run: |
          packer init custom-image.pkr.hcl
          packer fmt custom-image.pkr.hcl
          packer validate custom-image.pkr.hcl
          packer build custom-image.pkr.hcl
