name: Packer CI - PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  packer:
    name: Packer action - on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Packer init
        working-directory: ./packer
        run: packer init custom-image-centos.pkr.hcl

      - name: Packer fmt
        working-directory: ./packer
        run: packer fmt custom-image-centos.pkr.hcl

      - name: Packer validate
        working-directory: ./packer
        run: packer validate custom-image-centos.pkr.hcl